name: miscoches
description: Gestiona tus coches, mantenimientos, repostajes y gastos de forma sencilla
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Images
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "icon.png"
